/**
 * Wilayas Seed Data (Algeria - 58 Wilayas)
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('wilayas').del();

  // Inserts seed entries
  await knex('wilayas').insert([
    { code: 1, name: 'Adrar', name_fr: 'Adrar', name_ar: 'أدرار' },
    { code: 2, name: 'Chlef', name_fr: 'Chlef', name_ar: 'الشلف' },
    { code: 3, name: 'Laghouat', name_fr: 'Laghouat', name_ar: 'الأغواط' },
    { code: 4, name: 'Oum El Bouaghi', name_fr: 'Oum El Bouaghi', name_ar: 'أم البواقي' },
    { code: 5, name: 'Batna', name_fr: 'Batna', name_ar: 'باتنة' },
    { code: 6, name: 'Béjaïa', name_fr: 'Béjaïa', name_ar: 'بجاية' },
    { code: 7, name: 'Biskra', name_fr: 'Biskra', name_ar: 'بسكرة' },
    { code: 8, name: 'Béchar', name_fr: 'Béchar', name_ar: 'بشار' },
    { code: 9, name: 'Blida', name_fr: 'Blida', name_ar: 'البليدة' },
    { code: 10, name: 'Bouira', name_fr: 'Bouira', name_ar: 'البويرة' },
    { code: 11, name: 'Tamanrasset', name_fr: 'Tamanrasset', name_ar: 'تمنراست' },
    { code: 12, name: 'Tébessa', name_fr: 'Tébessa', name_ar: 'تبسة' },
    { code: 13, name: 'Tlemcen', name_fr: 'Tlemcen', name_ar: 'تلمسان' },
    { code: 14, name: 'Tiaret', name_fr: 'Tiaret', name_ar: 'تيارت' },
    { code: 15, name: 'Tizi Ouzou', name_fr: 'Tizi Ouzou', name_ar: 'تيزي وزو' },
    { code: 16, name: 'Alger', name_fr: 'Alger', name_ar: 'الجزائر' },
    { code: 17, name: 'Djelfa', name_fr: 'Djelfa', name_ar: 'الجلفة' },
    { code: 18, name: 'Jijel', name_fr: 'Jijel', name_ar: 'جيجل' },
    { code: 19, name: 'Sétif', name_fr: 'Sétif', name_ar: 'سطيف' },
    { code: 20, name: 'Saïda', name_fr: 'Saïda', name_ar: 'سعيدة' },
    { code: 21, name: 'Skikda', name_fr: 'Skikda', name_ar: 'سكيكدة' },
    { code: 22, name: 'Sidi Bel Abbès', name_fr: 'Sidi Bel Abbès', name_ar: 'سيدي بلعباس' },
    { code: 23, name: 'Annaba', name_fr: 'Annaba', name_ar: 'عنابة' },
    { code: 24, name: 'Guelma', name_fr: 'Guelma', name_ar: 'قالمة' },
    { code: 25, name: 'Constantine', name_fr: 'Constantine', name_ar: 'قسنطينة' },
    { code: 26, name: 'Médéa', name_fr: 'Médéa', name_ar: 'المدية' },
    { code: 27, name: 'Mostaganem', name_fr: 'Mostaganem', name_ar: 'مستغانم' },
    { code: 28, name: 'M\'Sila', name_fr: 'M\'Sila', name_ar: 'المسيلة' },
    { code: 29, name: 'Mascara', name_fr: 'Mascara', name_ar: 'معسكر' },
    { code: 30, name: 'Ouargla', name_fr: 'Ouargla', name_ar: 'ورقلة' },
    { code: 31, name: 'Oran', name_fr: 'Oran', name_ar: 'وهران' },
    { code: 32, name: 'El Bayadh', name_fr: 'El Bayadh', name_ar: 'البيض' },
    { code: 33, name: 'Illizi', name_fr: 'Illizi', name_ar: 'اليزي' },
    { code: 34, name: 'Bordj Bou Arréridj', name_fr: 'Bordj Bou Arréridj', name_ar: 'برج بوعريريج' },
    { code: 35, name: 'Boumerdès', name_fr: 'Boumerdès', name_ar: 'بومرداس' },
    { code: 36, name: 'El Tarf', name_fr: 'El Tarf', name_ar: 'الطارف' },
    { code: 37, name: 'Tindouf', name_fr: 'Tindouf', name_ar: 'تندوف' },
    { code: 38, name: 'Tissemsilt', name_fr: 'Tissemsilt', name_ar: 'تسمسيلت' },
    { code: 39, name: 'El Oued', name_fr: 'El Oued', name_ar: 'الوادي' },
    { code: 40, name: 'Khenchela', name_fr: 'Khenchela', name_ar: 'خنشلة' },
    { code: 41, name: 'Souk Ahras', name_fr: 'Souk Ahras', name_ar: 'سوق أهراس' },
    { code: 42, name: 'Tipaza', name_fr: 'Tipaza', name_ar: 'تيبازة' },
    { code: 43, name: 'Mila', name_fr: 'Mila', name_ar: 'ميلة' },
    { code: 44, name: 'Aïn Defla', name_fr: 'Aïn Defla', name_ar: 'عين الدفلى' },
    { code: 45, name: 'Naâma', name_fr: 'Naâma', name_ar: 'النعامة' },
    { code: 46, name: 'Aïn Témouchent', name_fr: 'Aïn Témouchent', name_ar: 'عين تموشنت' },
    { code: 47, name: 'Ghardaïa', name_fr: 'Ghardaïa', name_ar: 'غرداية' },
    { code: 48, name: 'Relizane', name_fr: 'Relizane', name_ar: 'غليزان' },
    { code: 49, name: 'El M\'Ghair', name_fr: 'El M\'Ghair', name_ar: 'المغير' },
    { code: 50, name: 'Touggourt', name_fr: 'Touggourt', name_ar: 'تقرت' },
    { code: 51, name: 'Djanet', name_fr: 'Djanet', name_ar: 'جانت' },
    { code: 52, name: 'Aïn Salah', name_fr: 'Aïn Salah', name_ar: 'عين صالح' },
    { code: 53, name: 'Aïn Guezzam', name_fr: 'Aïn Guezzam', name_ar: 'عين قزام' },
    { code: 54, name: 'Timimoun', name_fr: 'Timimoun', name_ar: 'تيميمون' },
    { code: 55, name: 'Bordj Badji Mokhtar', name_fr: 'Bordj Badji Mokhtar', name_ar: 'برج باجي مختار' },
    { code: 56, name: 'Ouled Djellal', name_fr: 'Ouled Djellal', name_ar: 'أولاد جلال' },
    { code: 57, name: 'Béni Abbès', name_fr: 'Béni Abbès', name_ar: 'بني عباس' },
    { code: 58, name: 'In Salah', name_fr: 'In Salah', name_ar: 'إن صالح' }
  ]);
};
